//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public int id { get; set; }
        public Nullable<int> cliente { get; set; }
        public Nullable<int> produto { get; set; }
        public string observacao { get; set; }
    
        public virtual cliente cliente1 { get; set; }
        public virtual produto produto1 { get; set; }
    }
}
