// <auto-generated />
namespace API.ConsumindoApiMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AlteradoTipopropriedadeNome : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlteradoTipopropriedadeNome));
        
        string IMigrationMetadata.Id
        {
            get { return "201809212008481_Alterado Tipo propriedade Nome"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
