// <auto-generated />
namespace API.ConsumindoApiMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CriadoModelosdeprodutoemarca : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CriadoModelosdeprodutoemarca));
        
        string IMigrationMetadata.Id
        {
            get { return "201809211940348_Criado Modelos de produto e marca"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
